"""remove razorpay and add qr fields

Revision ID: 41c2e4b7a899
Revises: razorpay_migration_001
Create Date: 2026-02-23 12:34:18.909309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41c2e4b7a899'
down_revision: Union[str, Sequence[str], None] = 'razorpay_migration_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bank_details_razorpay_contact_id'), table_name='user_bank_details')
    op.drop_table('user_bank_details')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='razorpay_webhook_events')
    op.drop_index(op.f('ix_webhook_events_is_processed'), table_name='razorpay_webhook_events')
    op.drop_index(op.f('ix_webhook_events_payout_id'), table_name='razorpay_webhook_events')
    op.drop_table('razorpay_webhook_events')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payout_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_reference_id'), table_name='payments')
    op.drop_table('payments')
    op.add_column('expense_requests', sa.Column('payment_qr_url', sa.String(length=500), nullable=True))
    op.add_column('expense_requests', sa.Column('payment_note', sa.Text(), nullable=True))
    op.drop_column('expense_requests', 'qr_url')
    op.drop_column('expense_requests', 'payee_vpa')
    op.drop_column('expense_requests', 'payment_qr_extracted_at')
    op.drop_column('expense_requests', 'payee_ifsc')
    op.drop_column('expense_requests', 'payment_status')
    op.drop_column('expense_requests', 'payee_bank_name')
    op.drop_column('expense_requests', 'payment_qr_data')
    op.drop_column('expense_requests', 'payment_type')
    op.drop_column('expense_requests', 'payee_name')
    op.drop_column('expense_requests', 'bill_urls')
    op.drop_column('expense_requests', 'payee_account_number')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'REQUESTOR', 'APPROVER', 'ACCOUNTANT', name='userrole'),
               type_=sa.Enum('ADMIN', 'REQUESTOR', 'APPROVER', 'ACCOUNTANT', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'REQUESTOR', 'APPROVER', 'ACCOUNTANT', name='userrole', native_enum=False),
               type_=postgresql.ENUM('ADMIN', 'REQUESTOR', 'APPROVER', 'ACCOUNTANT', name='userrole'),
               existing_nullable=False)
    op.add_column('expense_requests', sa.Column('payee_account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('bill_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('payee_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('payment_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('payment_qr_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('payee_bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('payment_status', postgresql.ENUM('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='paymentstatus'), autoincrement=False, nullable=False))
    op.add_column('expense_requests', sa.Column('payee_ifsc', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('payment_qr_extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('payee_vpa', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('expense_requests', sa.Column('qr_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('expense_requests', 'payment_note')
    op.drop_column('expense_requests', 'payment_qr_url')
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('upi_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('adjustment_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=50), server_default=sa.text("'manual_upi'::character varying"), autoincrement=False, nullable=True),
    sa.Column('razorpay_payout_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_fund_account_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_contact_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('razorpay_utr', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('vpa_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('beneficiary_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('initiated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('initiated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('webhook_received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('beneficiary_mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('razorpay_reference_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense_requests.id'], name='payments_expense_id_fkey'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], name='fk_payments_initiated_by'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('receipt_number', name='payments_receipt_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('transaction_id', name='payments_transaction_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_payments_razorpay_reference_id'), 'payments', ['razorpay_reference_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_payout_id'), 'payments', ['razorpay_payout_id'], unique=True)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
    op.create_table('razorpay_webhook_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('signature', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_signature_valid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('payout_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_webhook_events_payment_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('razorpay_webhook_events_pkey')),
    sa.UniqueConstraint('event_id', name=op.f('uq_webhook_events_event_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_webhook_events_payout_id'), 'razorpay_webhook_events', ['payout_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_is_processed'), 'razorpay_webhook_events', ['is_processed'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'razorpay_webhook_events', ['event_type'], unique=False)
    op.create_table('user_bank_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_holder_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('vpa_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_contact_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_fund_account_id_bank', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('razorpay_fund_account_id_vpa', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('verification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_bank_details_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_bank_details_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_bank_details_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_bank_details_razorpay_contact_id'), 'user_bank_details', ['razorpay_contact_id'], unique=False)
    # ### end Alembic commands ###
