"""add_deemed_approval_limit_to_organization

Revision ID: 8b66d01597f9
Revises: c8a4ec916be5
Create Date: 2025-12-30 16:24:11.394280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b66d01597f9'
down_revision: Union[str, Sequence[str], None] = 'c8a4ec916be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('deemed_approval_limit', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'deemed_approval_limit')
    # ### end Alembic commands ###
