"""add_request_type_to_expense

Revision ID: c8a4ec916be5
Revises: 8a49f702ae6b
Create Date: 2025-12-30 15:32:14.897081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a4ec916be5'
down_revision: Union[str, Sequence[str], None] = '8a49f702ae6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type
    expense_request_type = sa.Enum('PRE_APPROVED', 'POST_APPROVED', name='expenserequesttype')
    expense_request_type.create(op.get_bind(), checkfirst=True)
    
    # Add column with server default for existing rows
    op.add_column('expense_requests', 
        sa.Column('request_type', expense_request_type, 
                  nullable=False, 
                  server_default='PRE_APPROVED'))
    
    # Remove server default after column is created
    op.alter_column('expense_requests', 'request_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_requests', 'request_type')
    # ### end Alembic commands ###
